import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import NavbarComponent from "../components/navbar/";
import Login from "../pages/auth/login";
// import Home from "../pages/home";
import UnverifiedPage from "../components/verification/homeprotect";

export default function Home() {
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      {/* <Home /> */}
      <Login />
      {/* <UnverifiedPage /> */}
    </>
  );
}
